#Lumeon client settings
[general]
	#Fully enables or disables Lumeon.
	enabled = true
	#Enables or disables Lumeon LOD rendering.
	enable_rendering = true
	#Enables conversion of freshly built chunks into LOD data.
	ingest_enabled = true
	#LOD render distance in Minecraft chunks.
	# Default: 253
	# Range: 20 ~ 2048
	render_distance_chunks = 170
	#Number of worker threads Lumeon can use.
	# Default: 6
	# Range: 1 ~ 8
	service_threads = 6
	#Fraction of worker frame time Lumeon can use for background work.
	# Default: 0.550000011920929
	# Range: 0.1 ~ 0.85
	worker_runtime_ratio = 0.550000011920929

#Lumeon fog and cloud settings
[rendering]
	#Enables or disables the Lumeon fog effect.
	render_lumeon_fog = true
	#Distance in chunks used by Lumeon's sky fog.
	# Default: 4
	# Range: 0 ~ 1024
	sky_fog_distance = 4
	#Strength of the Lumeon fog effect.
	# Default: 3.0
	# Range: 0.0 ~ 3.0
	fog_intensity = 3.0
	#Additional density for the Lumeon fog effect.
	# Default: 5.0
	# Range: 0.0 ~ 5.0
	fog_density = 5.0
	#Distance used by Lumeon's cloud rendering support.
	# Default: 265
	# Range: 0 ~ 265
	cloud_distance = 265
